### ISSUE TITLE
eval.py里面遇到的问题

### ISSUE THREAD

**Issue by divided7** [Zzh-tju/CIoU#21]

**Comment by divided7** [comment]
修改完缩进问题和等号的问题后，遇到了问题：
Traceback (most recent call last):
  File "eval.py", line 1156, in <module>
    evaluate(net, dataset)
  File "eval.py", line 980, in evaluate
    preds = net(batch)
  File "/home/user1/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/CIoU/yolact.py", line 676, in forward
    return self.detect(pred_outs, self)
  File "/home/user1/CIoU/layers/functions/detection.py", line 76, in __call__
    result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data)
  File "/home/user1/CIoU/layers/functions/detection.py", line 120, in detect
    boxes, masks, classes, scores = self.cluster_nms(boxes, masks, scores, self.nms_thresh, self.top_k)
  File "/home/user1/CIoU/layers/functions/detection.py", line 311, in cluster_nms
    scores, idx = scores.sort(1, descending=True)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
参考之前的issues使用fast_nms还是不行

**Comment by kafei123456** [comment]
> 修改完缩进问题和等号的问题后，遇到了问题： Traceback (most recent call last): File "eval.py", line 1156, in evaluate(net, dataset) File "eval.py", line 980, in evaluate preds = net(batch) File "/home/user1/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/user1/CIoU/yolact.py", line 676, in forward return self.detect(pred_outs, self) File "/home/user1/CIoU/layers/functions/detection.py", line 76, in **call** result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data) File "/home/user1/CIoU/layers/functions/detection.py", line 120, in detect boxes, masks, classes, scores = self.cluster_nms(boxes, masks, scores, self.nms_thresh, self.top_k) File "/home/user1/CIoU/layers/functions/detection.py", line 311, in cluster_nms scores, idx = scores.sort(1, descending=True) IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 参考之前的issues使用fast_nms还是不行

你解决这个问题了吗？

**Comment by qq843626244** [comment]
> > 修改完缩进问题和等号的问题后，遇到了问题： Traceback (most recent call last): File "eval.py", line 1156, in evaluate(net, dataset) File "eval.py", line 980, in evaluate preds = net(batch) File "/home/user1/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/user1/CIoU/yolact.py", line 676, in forward return self.detect(pred_outs, self) File "/home/user1/CIoU/layers/functions/detection.py", line 76, in **call** result = self.detect(batch_idx, conf_preds, decoded_boxes, mask_data, inst_data) File "/home/user1/CIoU/layers/functions/detection.py", line 120, in detect boxes, masks, classes, scores = self.cluster_nms(boxes, masks, scores, self.nms_thresh, self.top_k) File "/home/user1/CIoU/layers/functions/detection.py", line 311, in cluster_nms scores, idx = scores.sort(1, descending=True) IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 参考之前的issues使用fast_nms还是不行
> 
> 你解决这个问题了吗？

请问你解决这个问题了吗
